version: '2'
services:
  preguntasmysql:
    image: mysql:5.7.21
    restart: always
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: preguntas
    container_name: preguntasdb
  preguntasadminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
